### ISSUE TITLE
ImportError on Startup

### ISSUE THREAD

**Issue by majovec** [TransendStudios/Trinket#10]
root@Fylkat:~/Trinket#  python startup.py
Traceback (most recent call last):
  File "startup.py", line 3, in <module>
    from trinket.trinket import Trinket
  File "/root/Trinket/trinket/trinket.py", line 21, in <module>
    from trinket.network.tcpserversocket import TCPServerSocket
ImportError: No module named network.tcpserversocket

**Comment by RedstoneAlmeida** [comment]
We are currently solving this problem.

**Comment by ImagicalGamer** [comment]
@majovec What OS are you using?

**Comment by ImagicalGamer** [comment]
I'm going to assume Linux since it's root@

**Comment by ImagicalGamer** [comment]
Try using f548ddedecd31defbf573c5fa6e7dafbd3a3df98 it should fix it.

**Comment by RedstoneAlmeida** [comment]
is not fixed ;-;

![image](https://cloud.githubusercontent.com/assets/15146680/26331058/563ecfe4-3f25-11e7-9149-32c00ec74582.png)

**Comment by ImagicalGamer** [comment]
print the current directory os.path.realpath(sys.argv[0]).replace(str(os.sep) + "startup.py", "")

**Comment by ImagicalGamer** [comment]
print it in startup.py and trinket.py

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26331107/9e17864e-3f25-11e7-9269-fa40fab58aaf.png)

**Comment by ImagicalGamer** [comment]
print not picture

**Comment by ImagicalGamer** [comment]
See how python is reading it.

**Comment by RedstoneAlmeida** [comment]
oh, okay sorry

**Comment by ImagicalGamer** [comment]
lol

**Comment by ImagicalGamer** [comment]
Not sure why it isn't throwing the error on Windows.

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26331269/686939b0-3f26-11e7-98b6-9c5775fe91ba.png)

**Comment by RedstoneAlmeida** [comment]
The error also happens when i try to start by start.sh on windows ...

**Comment by ImagicalGamer** [comment]
Try using python startup.py instead of the shell file on Linux.

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26331309/a2e6fc1c-3f26-11e7-9ea7-39270c51725e.png)

**Comment by RedstoneAlmeida** [comment]
I'm already doing this

**Comment by ImagicalGamer** [comment]
This is weird.

**Comment by ImagicalGamer** [comment]
use print(str(sys.path)) and see what it returns

**Comment by RedstoneAlmeida** [comment]
It's strange, does not it use ./startup.py in linux?

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26331414/1c4e2d32-3f27-11e7-9e1f-f11cad9de110.png)

**Comment by RedstoneAlmeida** [comment]
Is python2.7 plus is python3.5 just installed in the wrong folder

**Comment by ImagicalGamer** [comment]
It should be working.

**Comment by ImagicalGamer** [comment]
I'm not sure, it's being run on py 3.5 or it wouldn't startup.

**Comment by RedstoneAlmeida** [comment]
What would be the Import Error?

**Comment by ImagicalGamer** [comment]
I disabled Linux support for now, I'm gonna do some research.

**Comment by ImagicalGamer** [comment]
It works fine using python startup.py or start.cmd on windows. No idea for Linux

**Comment by RedstoneAlmeida** [comment]
Mine does not work with start.cmd

**Comment by ImagicalGamer** [comment]
Error?

**Comment by RedstoneAlmeida** [comment]
It opens and closes quickly

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26331756/03576d78-3f29-11e7-8ca0-040959ff051c.png)

**Comment by RedstoneAlmeida** [comment]
I just changed the from and import of place and left more organized, and changed the module

**Comment by ImagicalGamer** [comment]
Did it fix it @RedstoneAlmeida?

**Comment by RedstoneAlmeida** [comment]
I still can not, I'm trying.

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/26332121/1d4b05ee-3f2b-11e7-8b4d-c5490365a667.png)
python 3.5 is not error...

**Comment by ImagicalGamer** [comment]
I still can't find the issue.

**Comment by ImagicalGamer** [comment]
Run python -c "import sys, pprint; pprint.pprint(sys.path)" and post the contents here.

**Comment by RedstoneAlmeida** [comment]
Please, Install Python3.4+ or Python3.5
in Terminal:
python3 startup.py

![image](https://cloud.githubusercontent.com/assets/15146680/26374092/72f20362-3fda-11e7-8979-f64c25ef8621.png)

**Comment by RedstoneAlmeida** [comment]
Error in Connect
python3.4 and python3.5

![image](https://cloud.githubusercontent.com/assets/15146680/26376023/6792b3de-3fe1-11e7-8e75-f3366c349183.png)

**Comment by ImagicalGamer** [comment]
I think ik where thats coming from, I haven't finished a packet so its expecting data.

**Comment by ImagicalGamer** [comment]
So the startup error on Linux is fixed?

**Comment by RedstoneAlmeida** [comment]
yes, startup is fixed, decode error is not fixed

**Comment by ImagicalGamer** [comment]
Issue is resolved, don't use the "transfer" branch of Trinket with TrinketPM or vice versa.
